name: PHP Workflow

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest
      
    - name: PHP Code Style Fixer (php-cs-fixer)
      uses: StephaneBour/actions-php-cs-fixer@1.0
    
    - name: Run PHPUnit
      run: ./vendor/bin/phpunit tests
      
    - name: Code Climate Test Reporter
      uses: aktions/codeclimate-test-reporter@v1.0.3
      with:
        # The test reporter ID. This is a write-only ID that can only post test reports.
        codeclimate-test-reporter-id: b0195035d3bd681436f6710fc5b2d171170bffe036166d258b833f3c6a2074c3
        # The test reporter version. By default "latest" is used. If not explicitly set in semver format, caching will not work.
        command: after-build --coverage-input-type clover

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test
